build:
  version: "3.0"

accounts:
  message: "Welcome to SpringBank accounts related local APIs "
  contactDetails:
    name: "John Doe - Developer"
    email: "john@springbank.com"
  onCallSupport:
    - (555) 555-1234
    - (555) 523-1345
