build:
  version: "1.0"

loans:
  message: "Welcome to SpringBank loans related prod APIs "
  contactDetails:
    name: "Pelias Sudhir - Product Owner"
    email: "pelias@springbank.com"
  onCallSupport:
    - (723) 656-8709
    - (156) 342-0956